import type { Metadata } from "next";
import Link from "next/link";
import { PrintButton } from "@/src/components/print-button";
export const metadata: Metadata={title:"Paper abierto v0.1"};
const refs=[
  ["Simner, Cuskley & Kirby (2010)","What sound does that taste? Cross-modal mappings across gustation and audition.","https://pubmed.ncbi.nlm.nih.gov/20515002/","10.1068/p6591","20515002"],
  ["Crisinel & Spence (2010)","As bitter as a trombone: synesthetic correspondences in nonsynesthetes between tastes/flavors and musical notes.","https://pubmed.ncbi.nlm.nih.gov/20952795/","10.3758/APP.72.7.1994","20952795"],
  ["Reinoso Carvalho et al. (2017)","Smooth operator: Music modulates the perceived creaminess, sweetness, and bitterness of chocolate.","https://pubmed.ncbi.nlm.nih.gov/27784634/","10.1016/j.appet.2016.10.026","27784634"],
  ["Janata (2009)","The neural architecture of music-evoked autobiographical memories.","https://pubmed.ncbi.nlm.nih.gov/19240137/","10.1093/cercor/bhp008","19240137"],
  ["Kershaw & Running (2018)","Conditioning of human salivary flow using a visual cue for sour candy.","https://pubmed.ncbi.nlm.nih.gov/29778624/","10.1016/j.archoralbio.2018.05.010","29778624"],
  ["Avery, Carrington & Martin (2023)","A common neural code for representing imagined and inferred tastes.","https://pubmed.ncbi.nlm.nih.gov/36805499/","10.1016/j.pneurobio.2023.102423","36805499"],
];
export default function PaperPage(){return <main id="contenido" className="paper-page shell"><header className="paper-head"><p className="page-label">OPEN PAPER · V0.1 · 17 JUL 2026</p><h1>UMBRAL: An Open, Zero-Cost Platform for Adaptive Auditory-Perceptual Learning Experiments</h1><p>Lucas (founder and director) · Samuel (local possibility engine) · open contributors</p><div className="notice"><b>Estado:</b> protocolo y paper vivo de investigación abierta. No fue revisado por pares y no demuestra que UMBRAL produzca sabores, recuerdos o tratamientos.</div><div className="actions"><PrintButton/><Link className="button ghost" href="https://github.com/">Archivo original en GitHub (al publicar)</Link></div></header><article className="paper-body prose">
<h2>Resumen</h2><p>UMBRAL es una plataforma web abierta para estudiar si señales auditivas procedurales pueden adquirir relaciones reproducibles con estados perceptuales, emocionales o corporales. Propone protocolos adaptativos client-side con condiciones sham, omisión, transferencia y retest. No presupone que la hipótesis funcione: prioriza estimar cuándo falla, cuánto depende de expectativa y qué explicaciones alternativas sobreviven.</p>
<h2>Explicación simple</h2><p>Emparejamos un sonido nuevo con una experiencia simple. Después quitamos parte de la experiencia y preguntamos qué, si algo, reaparece. Repetimos con señales de control para distinguir aprendizaje de expectativa, familiaridad o azar.</p>
<h2>Antecedentes y problema</h2><p>La literatura muestra correspondencias entre sonido y gusto, modificación multisensorial del sabor durante el consumo, recuerdos autobiográficos evocados por música, condicionamiento salival mediante señales visuales y representaciones neurales compartidas para gustos imaginados e inferidos. Cada resultado sostiene un componente; ninguno demuestra la composición completa propuesta por UMBRAL.</p>
<div className="notice">La evidencia disponible sustenta componentes individuales del proyecto, como las asociaciones sonido-sabor, la modificación multisensorial del sabor, la evocación autobiográfica por música, el condicionamiento salival y la representación de gustos imaginados. No demuestra todavía que una firma auditiva pueda generar por sí sola un sabor completo o una experiencia autobiográfica específica.</div>
<h2>Hipótesis</h2><p>H1: después de aprendizaje, una señal auditiva producirá respuestas por encima de sham y de su línea de base en al menos una dimensión preespecificada. H2: una fracción de la respuesta sobrevivirá al fading y se repetirá en otra sesión. H3: una señal de segundo orden podrá adquirir parte de la relación. La hipótesis nula admite que las diferencias se expliquen por expectativa, demanda, familiaridad, orden o azar.</p>
<h2>Arquitectura experimental y métodos</h2><p>Los estímulos se describen mediante genomas versionados: semilla, frecuencia portadora, modulación, envolvente, duración, paneo, secuencia y hash. Se generan en Web Audio API con ganancia conservadora. El protocolo aleatoriza orden, oculta repeticiones y registra si ocurrió algo antes de revelar categorías. Atlas mapea asociaciones; Apprenticeship prueba adquisición y retirada; State Gate manipula preparación; Anchor estudia estados seguros elegidos.</p>
<h2>Controles y variables</h2><p>Controles: sham, estímulo solo, preparación sola, omisión, expectativa contradictoria, secuencias no apareadas y retest diferido. Variables primarias: respuesta espontánea, similitud objetivo, diferencia frente a control y reproducibilidad. Secundarias: confianza, expectativa, intensidad, latencia, categoría fenomenológica, habituación y efectos adversos.</p>
<h2>Análisis</h2><p>El plan usa tamaños de efecto con intervalos bootstrap, curvas por participante, comparaciones preespecificadas contra sham y modelos interpretables. Los datos faltantes no se imputan en análisis primario. No se convierten escalas ordinales en precisión falsa. Los análisis exploratorios se etiquetan y los resultados negativos se conservan.</p>
<h2>Seguridad, ética y privacidad</h2><p>Ganancia interna limitada, rampas anti-click, Stop global, pausas y advertencia de volumen. Sin trauma, ultrasonido, flashes, subliminales, micrófono, cámara ni condicionamiento fuera de sesión. El demo guarda IndexedDB local. La contribución agregada requiere consentimiento separado y revocable.</p>
<h2>Limitaciones y criterios de refutación</h2><p>El navegador no calibra dB SPL reales ni mide actividad neural. Las respuestas son autoinformes susceptibles a demanda y aprendizaje del procedimiento. La hipótesis central se considera no apoyada si la diferencia contra sham es trivial, inestable en retest, desaparece al controlar expectativa o coincide con una regla más simple de correspondencia espontánea. UMBRAL debe poder concluir “no encontramos nada”.</p>
<h2>Próximos experimentos</h2><ol><li>Sonido–color preregistrado con repetición oculta y retest a siete días.</li><li>Fading paramétrico para separar reconocimiento de reconstrucción.</li><li>Transferencia A2→A1 con sham balanceado.</li><li>State Gate factorial: silencio × carga visual × instrucción.</li><li>Anchor seguro con resultados centrados en estabilidad, no intensidad.</li></ol>
<h2>Referencias verificadas</h2><ol className="references">{refs.map(r=><li key={r[4]}><b>{r[0]}.</b> {r[1]} <a href={r[2]}>PMID {r[4]}</a>. DOI: <a href={"https://doi.org/"+r[3]}>{r[3]}</a>.</li>)}</ol>
<h2>Cómo citar</h2><p>UMBRAL contributors (2026). <i>UMBRAL: An Open, Zero-Cost Platform for Adaptive Auditory-Perceptual Learning Experiments</i>. Version 0.1-alpha. Software and living protocol.</p>
<h2>Historial</h2><p>v0.1 · 2026-07-17 · Protocolo inicial, arquitectura free-first, controles y seis referencias semilla verificadas.</p>
</article></main>}
