import type { Metadata } from "next";

export const metadata:Metadata={title:"Matriz de evidencia"};

const evidence=[
  {level:"Componente establecido",finding:"Hay correspondencias compartidas entre propiedades acústicas y gustos en tareas de emparejamiento.",limit:"Emparejar no equivale a percibir un gusto generado por sonido.",source:"Simner et al. 2010",href:"https://pubmed.ncbi.nlm.nih.gov/20515002/"},
  {level:"Componente establecido",finding:"Dulce/ácido se asociaron con notas más agudas; umami/amargo, con notas más graves.",limit:"La tarea fue explícita y familiaridad/agrado pudieron influir.",source:"Crisinel & Spence 2010",href:"https://pubmed.ncbi.nlm.nih.gov/20952795/"},
  {level:"Componente establecido",finding:"La música modificó atributos reportados mientras se probaba chocolate idéntico.",limit:"El chocolate estaba presente; no demuestra gusto desde audio solo.",source:"Reinoso Carvalho et al. 2017",href:"https://pubmed.ncbi.nlm.nih.gov/27784634/"},
  {level:"Mecanismo plausible",finding:"Música familiar puede evocar recuerdos autobiográficos.",limit:"Música conocida no equivale a una firma procedural nueva.",source:"Janata 2009",href:"https://pubmed.ncbi.nlm.nih.gov/19240137/"},
  {level:"Componente establecido",finding:"Una señal visual emparejada con caramelo ácido condicionó flujo salival.",limit:"Salivar no es saborear y la señal no era auditiva.",source:"Kershaw & Running 2018",href:"https://pubmed.ncbi.nlm.nih.gov/29778624/"},
  {level:"Mecanismo plausible",finding:"Gustos imaginados e inferidos compartieron información multivariable en ínsula dorsal media.",limit:"Solapamiento neural no demuestra equivalencia subjetiva ni causalidad auditiva.",source:"Avery et al. 2023",href:"https://pubmed.ncbi.nlm.nih.gov/36805499/"},
  {level:"Componente establecido",finding:"La integración gusto–olor congruente dependió de experiencia y reclutó una red multisensorial.",limit:"Los estímulos químicos fueron administrados físicamente.",source:"Small et al. 2004",href:"https://pubmed.ncbi.nlm.nih.gov/15102894/"},
  {level:"Mecanismo plausible",finding:"Omisiones inesperadas en secuencias auditivas produjeron respuestas jerárquicas medibles con EEG/MEG.",limit:"UMBRAL no mide EEG/MEG y no puede inferir esas respuestas.",source:"Wacongne et al. 2011",href:"https://pubmed.ncbi.nlm.nih.gov/22147913/"},
  {level:"Componente establecido",finding:"El aprendizaje auditivo mejoró identificación, con transferencia dependiente del material.",limit:"Aprender habla degradada no prueba asociación emocional crossmodal.",source:"Loebach et al. 2008",href:"https://pubmed.ncbi.nlm.nih.gov/18247913/"},
  {level:"Componente establecido",finding:"Mapeos estructurados imagen–sonido se aprendieron y generalizaron en 60 adultos.",limit:"Sustitución sensorial no demuestra qualia inducida por sonido.",source:"Kucinkas et al. 2025",href:"https://pubmed.ncbi.nlm.nih.gov/41339357/"},
  {level:"Evidencia mixta",finding:"Batidos binaurales muestran respuestas auditivas específicas pero entrainment débil y sin modulación de humor en un control activo.",limit:"No justifica afirmaciones terapéuticas, cognitivas ni de activación sin instrumental.",source:"Orozco Perez et al. 2020",href:"https://pubmed.ncbi.nlm.nih.gov/32066611/"},
  {level:"Guía oficial",finding:"Escucha segura depende de nivel, duración y exposición acumulada.",limit:"El porcentaje del dispositivo no calibra dB SPL en el oído.",source:"WHO/ITU 2019",href:"https://www.who.int/publications/i/item/9789241515276"},
];

export default function SciencePage(){return <main id="contenido" className="content-page shell">
  <div className="page-label">MATRIZ DE EVIDENCIA · VERIFICADA 17 JUL 2026</div>
  <h1>La evidencia sostiene piezas, no la conclusión completa</h1>
  <p className="intro">UMBRAL separa hallazgos establecidos, mecanismos plausibles, evidencia mixta y afirmaciones todavía no demostradas. Cada fila enlaza una fuente primaria o guía oficial y muestra el límite que impide exagerarla.</p>
  <div className="notice">Ninguna fuente demuestra que una firma auditiva nueva produzca por sí sola un sabor completo, un recuerdo específico o una activación neural determinada.</div>
  <div className="table-scroll" role="region" aria-label="Matriz de evidencia" tabIndex={0}><table className="evidence-table"><thead><tr><th>Clase</th><th>Qué encontró</th><th>Qué no permite concluir</th><th>Fuente</th></tr></thead><tbody>{evidence.map(row=><tr key={row.source}><td>{row.level}</td><td>{row.finding}</td><td>{row.limit}</td><td><a href={row.href}>{row.source}</a></td></tr>)}</tbody></table></div>
  <section className="prose"><h2>Qué podría refutar UMBRAL</h2><p>Una diferencia trivial frente a sham, inestabilidad en retest, dependencia completa de expectativa o una regla de correspondencia espontánea más simple bastan para no apoyar la hipótesis. Un resultado negativo no se oculta ni se transforma en una promesa nueva.</p><h2>Alcance de la búsqueda</h2><p>La búsqueda fue dirigida y verificó las seis referencias semilla, aprendizaje auditivo, sustitución sensorial, omisión, condicionamiento de segundo orden, integración gusto–olor, batidos y seguridad auditiva. Es una base para el MVP, no una revisión sistemática. Antes de reclutar se requiere búsqueda reproducible, doble cribado, evaluación de sesgo y preregistro.</p></section>
  <section className="prose english-summary" lang="en"><p className="page-label">ENGLISH SUMMARY</p><h2>Evidence supports components, not the full claim</h2><p>Primary studies support sound–taste matching, multisensory changes while food is present, music-evoked autobiographical memory, conditioned salivation, learnable image-to-sound mappings, and auditory omission responses. They do not show that a novel sound alone creates a complete taste or a specific memory. UMBRAL measures reports and behavior, not neural activity.</p></section>
</main>}
