"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { UmbralAudioEngine } from "@/src/lib/audio/engine";
import { buildProtocol, type TrialPlan } from "@/src/lib/protocol-engine";
import { genomeFromSeed, hashGenome } from "@/src/lib/stimulus-genome";
import { clearLocal, exportLocal, saveLocal } from "@/src/lib/local-store";
import { decide } from "@/src/lib/possibility-engine";
import { syncLocalSessions } from "@/src/lib/supabase/sync";

type Lab = "atlas" | "apprenticeship" | "state" | "anchor";
type Stage = "intro" | "calibrate" | "run" | "respond" | "result";
const labCopy: Record<Lab,{name:string;question:string;detail:string}> = {
  atlas:{name:"Atlas",question:"¿Qué aparece espontáneamente?",detail:"Sonido–color, sonido–forma, repeticiones ocultas y sham."},
  apprenticeship:{name:"Apprenticeship",question:"¿Qué queda cuando retiramos una parte?",detail:"Aprendizaje, fading, omisión y transferencia."},
  state:{name:"State Gate",question:"¿El estado previo cambia la respuesta?",detail:"Preparación, carga visual, silencio y expectativas contradictorias."},
  anchor:{name:"Anchor",question:"¿Una firma puede acompañar un estado seguro?",detail:"Sólo recuerdos seguros o refugios imaginados. Nunca trauma."},
};

export function DemoLab() {
  const [lab,setLab] = useState<Lab>("atlas"); const [stage,setStage] = useState<Stage>("intro"); const [trialIndex,setTrialIndex] = useState(0); const [occurred,setOccurred] = useState<boolean|null>(null); const [category,setCategory] = useState("ninguna"); const [confidence,setConfidence] = useState(50); const [message,setMessage] = useState(""); const [consent,setConsent] = useState(false); const [lang,setLang] = useState<"es"|"en">("es");
  const engine = useRef<UmbralAudioEngine|null>(null); const protocol = useMemo(() => buildProtocol(41027, 8), []); const trial: TrialPlan = protocol[trialIndex] ?? protocol[0]; const genome = useMemo(() => genomeFromSeed(trial.seed, trial.condition === "sham"), [trial]);
  useEffect(() => { engine.current = new UmbralAudioEngine(); const stop = () => engine.current?.stop(); window.addEventListener("umbral:stop",stop); navigator.serviceWorker?.register("/sw.js").catch(() => undefined); return () => { window.removeEventListener("umbral:stop",stop); void engine.current?.close(); }; },[]);
  const start = () => { setStage("calibrate"); setMessage(""); };
  const play = async () => { setStage("run"); setOccurred(null); setCategory("ninguna"); await engine.current?.play(genome); window.setTimeout(() => setStage("respond"), genome.durationMs + 150); };
  const saveResponse = async () => { const payload = { lab, trial, genomeHash: hashGenome(genome), occurred, category, confidence, decision: decide(trial.condition === "sham" ? "skeptic" : "cartographer", trial.seed) }; await saveLocal({ id: crypto.randomUUID(), createdAt: new Date().toISOString(), kind:"session", payload }); if (trialIndex < protocol.length - 1) { setTrialIndex(v => v + 1); setStage("calibrate"); } else setStage("result"); };
  const download = async () => { const blob = new Blob([await exportLocal()],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download="umbral-local-export.json";a.click();URL.revokeObjectURL(url);setMessage("Exportación creada en este dispositivo."); };
  const erase = async () => { await clearLocal(); setTrialIndex(0); setStage("intro"); setMessage("Datos locales eliminados."); };
  const sync = async () => { try { const count=await syncLocalSessions(); setMessage(String(count)+" sesiones sincronizadas por tu acción."); } catch(error) { setMessage(error instanceof Error?error.message:"No se pudo sincronizar."); } };
  const t = lang === "es" ? {local:"MODO LOCAL",privacy:"Tus resultados permanecen en este dispositivo y no forman parte de la investigación colectiva.",start:"Comenzar calibración",listen:"Escuchar señal",question:"¿Ocurrió algo?",yes:"Sí, algo ocurrió",no:"No noté nada",confidence:"Confianza",save:"Guardar y continuar"} : {local:"LOCAL MODE",privacy:"Your results stay on this device and are not part of collective research.",start:"Start calibration",listen:"Play signal",question:"Did anything happen?",yes:"Yes, something happened",no:"I noticed nothing",confidence:"Confidence",save:"Save and continue"};
  return <div className="demo-shell">
    <header className="demo-top"><div><span className="local-badge">● {t.local}</span><h1>Laboratorio perceptual</h1><p>{t.privacy}</p></div><button className="lang-button" onClick={() => setLang(lang === "es" ? "en" : "es")}>{lang === "es" ? "EN" : "ES"}</button></header>
    <div className="demo-layout"><aside className="lab-nav" aria-label="Laboratorios">{(Object.keys(labCopy) as Lab[]).map((id,i)=><button key={id} className={lab===id?"selected":""} onClick={()=>{engine.current?.stop();setLab(id);setStage("intro");setTrialIndex(0)}}><span>0{i+1}</span><b>{labCopy[id].name}</b><small>{labCopy[id].question}</small></button>)}</aside>
      <section className="lab-stage" aria-live="polite"><div className="trial-meta"><span>{labCopy[lab].name.toUpperCase()}</span>{stage!=="intro"&&<span>ENSAYO {trialIndex+1}/{protocol.length}</span>}</div>
        {stage==="intro"&&<div className="stage-card"><p className="kicker">PREGUNTA DEL LABORATORIO</p><h2>{labCopy[lab].question}</h2><p>{labCopy[lab].detail}</p>{lab==="anchor"&&<div className="safety-box">Elegí únicamente un estado seguro: calidez, pertenencia, alivio, curiosidad, ternura o amplitud. No uses trauma ni recuerdos inciertos.</div>}<label className="consent-check"><input type="checkbox" checked={consent} onClick={e=>setConsent(e.currentTarget.checked)} readOnly/> Entiendo que esto es investigación exploratoria, puedo detenerme y el volumen debe permanecer cómodo.</label><button className="button primary" disabled={!consent} onClick={start}>{t.start} →</button></div>}
        {stage==="calibrate"&&<div className="stage-card centered"><p className="kicker">ANTES DE ESCUCHAR</p><h2>Volumen bajo y cómodo</h2><p>UMBRAL no puede medir decibeles en tus auriculares. Empezá con el volumen del dispositivo por debajo del 60%. Detenete ante cualquier molestia.</p><div className="stimulus-preview"><span>{genome.sham?"SHAM":"SEÑAL"}</span><b>{hashGenome(genome)}</b></div><button className="button primary" onClick={play}>{t.listen} ▶</button></div>}
        {stage==="run"&&<div className="stage-card centered"><div className={trial.target==="color"?"visual-stimulus color":"visual-stimulus shape"} aria-label={trial.target==="color"?"Estímulo de color":"Estímulo de forma"}/><p>Escuchando una señal procedural…</p><button className="button ghost" onClick={()=>{engine.current?.stop();setStage("respond")}}>Detener y responder</button></div>}
        {stage==="respond"&&<div className="stage-card"><p className="kicker">RESPONDÉ ANTES DE VER CATEGORÍAS</p><h2>{t.question}</h2><div className="binary"><button className={occurred===true?"chosen":""} onClick={()=>setOccurred(true)}>{t.yes}</button><button className={occurred===false?"chosen":""} onClick={()=>setOccurred(false)}>{t.no}</button></div>{occurred===true&&<div className="response-detail"><label>¿Qué se parece más?<select value={category} onChange={e=>setCategory(e.target.value)}><option value="ninguna">No sé / otra cosa</option><option value="color">Color</option><option value="forma">Forma</option><option value="textura">Textura</option><option value="temperatura">Temperatura</option><option value="movimiento">Movimiento</option><option value="cuerpo">Estado corporal</option><option value="emocion">Emoción</option><option value="recuerdo">Recuerdo o imagen</option></select></label><label>{t.confidence}: {confidence}%<input type="range" min="0" max="100" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/></label></div>}<button className="button primary" disabled={occurred===null} onClick={saveResponse}>{t.save} →</button></div>}
        {stage==="result"&&<div className="stage-card"><p className="kicker">RESULTADO LOCAL · N={protocol.length}</p><h2>No alcanza para concluir.</h2><p>Completaste una secuencia balanceada con repetición, sham, omisión y transferencia. Una sesión puede mostrar consistencia aparente por azar, expectativa o familiaridad. El próximo paso válido es un retest en otro día.</p><div className="result-bars"><div><span>Calidad de datos</span><i style={{width:"82%"}}/></div><div><span>Incertidumbre</span><i style={{width:"68%"}}/></div><div><span>Necesidad de retest</span><i style={{width:"94%"}}/></div></div><button className="button primary" onClick={download}>Exportar JSON</button><button className="button ghost" onClick={()=>{setTrialIndex(0);setStage("intro")}}>Reiniciar</button></div>}
        {message&&<p className="local-message">{message}</p>}</section>
    </div><div className="data-tools"><button onClick={download}>Exportar todos los datos locales</button><button onClick={sync}>Sincronizar ahora (opcional)</button><button onClick={erase}>Eliminar completamente y reiniciar</button></div>
  </div>;
}
