-- UMBRAL v0.1 compact schema. No Storage, Realtime, Edge Functions, cron or service role in clients.
create extension if not exists pgcrypto;

create type public.app_role as enum ('participant','researcher','admin');
create type public.record_status as enum ('draft','published','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text check(char_length(display_name)<=80), locale text not null default 'es' check(locale in('es','en')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles (user_id uuid not null references auth.users(id) on delete cascade, role public.app_role not null default 'participant', granted_at timestamptz not null default now(), primary key(user_id,role));
create table public.consent_documents (id uuid primary key default gen_random_uuid(), kind text not null, version text not null, locale text not null check(locale in('es','en')), body_hash text not null, body text not null, published_at timestamptz, unique(kind,version,locale));
create table public.user_consents (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, document_id uuid not null references public.consent_documents(id), granted boolean not null, recorded_at timestamptz not null default now(), withdrawn_at timestamptz, client_snapshot jsonb not null default '{}'::jsonb, unique(user_id,document_id,recorded_at));
create table public.research_sources (id uuid primary key default gen_random_uuid(), title text not null, authors text[] not null default '{}', publication_year int check(publication_year between 1800 and 2200), journal text, doi text unique, pmid text unique, evidence_class text not null, verified_at timestamptz, metadata jsonb not null default '{}'::jsonb, status public.record_status not null default 'draft', created_at timestamptz not null default now());
create table public.hypotheses (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, statement text not null, falsification_criteria text not null, status public.record_status not null default 'draft', created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.protocols (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, summary text not null, status public.record_status not null default 'draft', created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.protocol_versions (id uuid primary key default gen_random_uuid(), protocol_id uuid not null references public.protocols(id) on delete restrict, version text not null, specification jsonb not null, specification_hash text not null, published_at timestamptz, created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(protocol_id,version));
create table public.stimulus_genomes (id uuid primary key default gen_random_uuid(), owner_id uuid references auth.users(id) on delete cascade, seed bigint not null, engine_version text not null, parameters jsonb not null, config_hash text not null, created_at timestamptz not null default now(), unique(owner_id,config_hash));
create table public.perceptual_chords (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, label text, component_genomes uuid[] not null default '{}', target_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.experiments (id uuid primary key default gen_random_uuid(), protocol_version_id uuid not null references public.protocol_versions(id), title text not null, status public.record_status not null default 'draft', opens_at timestamptz, closes_at timestamptz, created_by uuid references auth.users(id), created_at timestamptz not null default now());
create table public.sessions (id uuid primary key, user_id uuid not null references auth.users(id) on delete cascade, experiment_id uuid references public.experiments(id), protocol_version_id uuid references public.protocol_versions(id), source text not null default 'web', status text not null check(status in('started','completed','abandoned','invalid')), started_at timestamptz not null default now(), completed_at timestamptz, client_snapshot jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.trials (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.sessions(id) on delete cascade, trial_index int not null check(trial_index>=0), condition text not null, stimulus_genome_id uuid references public.stimulus_genomes(id), planned jsonb not null, presented_at timestamptz, created_at timestamptz not null default now(), unique(session_id,trial_index));
create table public.responses (id uuid primary key default gen_random_uuid(), trial_id uuid not null references public.trials(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, occurred boolean, category text, confidence smallint check(confidence between 0 and 100), expectation smallint check(expectation between 0 and 100), latency_ms int check(latency_ms>=0), value jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(trial_id,user_id));
create table public.phenomenology_reports (id uuid primary key default gen_random_uuid(), response_id uuid not null references public.responses(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, kind text not null, report_text text check(char_length(report_text)<=2000), qualities jsonb not null default '{}'::jsonb, free_text_consent_id uuid references public.user_consents(id), created_at timestamptz not null default now());
create table public.personal_models (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, algorithm text not null, algorithm_version text not null, model jsonb not null, training_hashes text[] not null default '{}', created_at timestamptz not null default now(), superseded_at timestamptz);
create table public.algorithm_decisions (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.sessions(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null, algorithm text not null, algorithm_version text not null, data_used jsonb not null, weights jsonb not null, reason text not null, alternative text not null, risk text not null, uncertainty numeric not null check(uncertainty>=0), next_control text not null, output jsonb not null, created_at timestamptz not null default now());
create table public.adverse_events (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, session_id uuid references public.sessions(id) on delete set null, severity text not null check(severity in('mild','moderate','serious')), category text not null, description text check(char_length(description)<=2000), action_taken text, created_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references auth.users(id));
create table public.feature_flags (key text primary key, enabled boolean not null default false, description text not null, updated_at timestamptz not null default now(), updated_by uuid references auth.users(id));
create table public.audit_events (id bigint generated always as identity primary key, actor_id uuid references auth.users(id), action text not null, table_name text not null, record_id uuid, detail jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.deletion_requests (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, requested_at timestamptz not null default now(), status text not null default 'requested' check(status in('requested','processing','completed','rejected')), completed_at timestamptz, note text);

create index sessions_user_created_idx on public.sessions(user_id,created_at desc);
create index trials_session_idx on public.trials(session_id,trial_index);
create index responses_user_created_idx on public.responses(user_id,created_at desc);
create index algorithm_decisions_session_idx on public.algorithm_decisions(session_id);
create index adverse_events_review_idx on public.adverse_events(reviewed_at) where reviewed_at is null;
create index user_consents_user_kind_idx on public.user_consents(user_id,recorded_at desc);

create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=required_role) $$;
revoke all on function public.has_role(public.app_role) from public; grant execute on function public.has_role(public.app_role) to authenticated;
create or replace function public.protect_protocol_version() returns trigger language plpgsql as $$ begin raise exception 'Published protocol versions are immutable'; end $$;
create trigger protocol_versions_immutable before update or delete on public.protocol_versions for each row when (old.published_at is not null) execute function public.protect_protocol_version();

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.consent_documents enable row level security; alter table public.user_consents enable row level security; alter table public.research_sources enable row level security; alter table public.hypotheses enable row level security; alter table public.protocols enable row level security; alter table public.protocol_versions enable row level security; alter table public.stimulus_genomes enable row level security; alter table public.perceptual_chords enable row level security; alter table public.experiments enable row level security; alter table public.sessions enable row level security; alter table public.trials enable row level security; alter table public.responses enable row level security; alter table public.phenomenology_reports enable row level security; alter table public.personal_models enable row level security; alter table public.algorithm_decisions enable row level security; alter table public.adverse_events enable row level security; alter table public.feature_flags enable row level security; alter table public.audit_events enable row level security; alter table public.deletion_requests enable row level security;

create policy profiles_self on public.profiles for all to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy roles_self_read on public.user_roles for select to authenticated using(user_id=auth.uid());
create policy roles_admin on public.user_roles for all to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy consent_docs_read on public.consent_documents for select to authenticated using(published_at is not null);
create policy consent_docs_admin on public.consent_documents for all to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy consents_self on public.user_consents for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy sources_public on public.research_sources for select to anon,authenticated using(status='published');
create policy sources_researcher on public.research_sources for all to authenticated using(public.has_role('researcher') or public.has_role('admin')) with check(public.has_role('researcher') or public.has_role('admin'));
create policy hypotheses_public on public.hypotheses for select to anon,authenticated using(status='published');
create policy hypotheses_researcher on public.hypotheses for all to authenticated using(public.has_role('researcher') or public.has_role('admin')) with check(public.has_role('researcher') or public.has_role('admin'));
create policy protocols_public on public.protocols for select to anon,authenticated using(status='published');
create policy protocols_researcher on public.protocols for all to authenticated using(public.has_role('researcher') or public.has_role('admin')) with check(public.has_role('researcher') or public.has_role('admin'));
create policy protocol_versions_public on public.protocol_versions for select to anon,authenticated using(published_at is not null);
create policy protocol_versions_insert on public.protocol_versions for insert to authenticated with check(public.has_role('researcher') or public.has_role('admin'));
create policy genomes_self on public.stimulus_genomes for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy chords_self on public.perceptual_chords for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy experiments_public on public.experiments for select to anon,authenticated using(status='published');
create policy experiments_researcher on public.experiments for all to authenticated using(public.has_role('researcher') or public.has_role('admin')) with check(public.has_role('researcher') or public.has_role('admin'));
create policy sessions_self on public.sessions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy trials_self on public.trials for all to authenticated using(exists(select 1 from public.sessions s where s.id=session_id and s.user_id=auth.uid())) with check(exists(select 1 from public.sessions s where s.id=session_id and s.user_id=auth.uid()));
create policy responses_self on public.responses for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy phenomenology_self on public.phenomenology_reports for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy models_self on public.personal_models for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy decisions_self on public.algorithm_decisions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy adverse_insert_self on public.adverse_events for insert to authenticated with check(user_id=auth.uid());
create policy adverse_read_self on public.adverse_events for select to authenticated using(user_id=auth.uid() or public.has_role('admin'));
create policy adverse_admin_update on public.adverse_events for update to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy flags_public on public.feature_flags for select to anon,authenticated using(true);
create policy flags_admin on public.feature_flags for all to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
create policy audit_admin on public.audit_events for select to authenticated using(public.has_role('admin'));
create policy deletion_self on public.deletion_requests for insert to authenticated with check(user_id=auth.uid());
create policy deletion_read_self on public.deletion_requests for select to authenticated using(user_id=auth.uid() or public.has_role('admin'));
create policy deletion_admin on public.deletion_requests for update to authenticated using(public.has_role('admin')) with check(public.has_role('admin'));
