import { genomeFromSeed, mulberry32, type StimulusGenome } from "@/src/lib/stimulus-genome";

export type Role = "explorer" | "composer" | "optimizer" | "skeptic" | "cartographer" | "anomaly-keeper";
export type AlgorithmDecision = { role: Role; algorithm: string; version: "0.1"; data: string[]; weights: Record<string, number>; reason: string; alternative: string; risk: string; uncertainty: number; nextControl: string; output: StimulusGenome };
export type Observation = { genome: StimulusGenome; similarity: number; controlDifference: number; reproducibility: number; expectation: number; adverse: number; confidence: number };

export function scoreObservation(o: Observation) { const positive = o.similarity * o.controlDifference * o.reproducibility * o.confidence; const penalties = o.adverse + o.expectation * 0.45; return Number((positive - penalties).toFixed(4)); }
export function latinHypercube(seed: number, count: number, dimensions: number) { const random = mulberry32(seed); return Array.from({ length: count }, (_, row) => Array.from({ length: dimensions }, (_, d) => ((row + random()) / count + d / count) % 1)); }
export function decide(role: Role, seed: number, observations: Observation[] = []): AlgorithmDecision { const best = observations.toSorted((a,b) => scoreObservation(b) - scoreObservation(a))[0]; const baseSeed = best ? best.genome.seed + seed : seed; const output = genomeFromSeed(baseSeed, role === "skeptic"); const reasons: Record<Role,string> = { explorer: "Cubrir una región poco muestreada", composer: "Construir una secuencia reproducible", optimizer: "Acercarse al objetivo observado", skeptic: "Separar respuesta de expectativa", cartographer: "Mapear vecindad estímulo–respuesta", "anomaly-keeper": "Repetir una señal atípica sin descartarla" }; return { role, algorithm: role === "explorer" ? "latin-hypercube" : role === "optimizer" ? "interpretable-grid-search" : "seeded-rule-set", version: "0.1", data: observations.map(o => String(o.genome.seed)), weights: { similarity: 1, reproducibility: 1, controlDifference: 1, expectationPenalty: -0.45, adversePenalty: -1 }, reason: reasons[role], alternative: "orden aleatorio balanceado", risk: "sobreajuste a pocas respuestas", uncertainty: observations.length ? 1 / Math.sqrt(observations.length) : 1, nextControl: role === "skeptic" ? "sham audible equivalente" : "retest con semilla oculta", output };
}
